FROM rfocosi/synchronet-bbs:base

RUN make -C /sbbs-static/ minimal install

RUN rm -rf $SBBS_STATIC_DIR/src/ $SBBS_STATIC_DIR/3rdp/ $SBBS_STATIC_DIR/Makefile && \
    apt purge -y build-essential gcc dpkg-dev g++ libc-dev make \
                 pkg-config autoconf && \
    apt autoremove -y && \
    apt clean -y
