FROM debian:bullseye

ENV SBBS_STATIC_DIR=/sbbs-static/
ENV SBBSCTRL=/sbbs/ctrl

WORKDIR $SBBS_STATIC_DIR

RUN apt update && \
    apt upgrade -y && \
    apt install -y build-essential pkg-config autoconf \
                   cvs zip libnspr4-dev \
                   libcrypto++-dev libssl-dev avr-libc liblhasa-dev \
                   libxbase64-dev libcap2-dev lib32ncurses-dev zip python2 \
                   wget rsync

RUN mkdir -p $SBBS_STATIC_DIR

COPY GNUmakefile $SBBS_STATIC_DIR
COPY startup.sh /
RUN chmod +x /startup.sh

RUN mkdir -p /sbbs/

CMD ["/startup.sh"]
