FROM debian:bullseye

RUN apt update && \
    apt install -y build-essential pkg-config autoconf \
                   libnspr4-dev libssl-dev avr-libc liblhasa-dev \
                   libxbase64-dev libcap2-dev lib32ncurses-dev zip python2

ENV SBBS_STATIC_DIR=/sbbs-static/
ENV SBBSUSER=sbbs
ENV SBBSGROUP=sbbs
ENV SBBSCTRL=/sbbs/ctrl

WORKDIR $SBBS_STATIC_DIR

RUN mkdir -p /sbbs/
RUN mkdir -p $SBBS_STATIC_DIR

ADD src/sbbs-src.tgz $SBBS_STATIC_DIR
ADD src/sbbs-init.tgz $SBBS_STATIC_DIR
ADD Makefile $SBBS_STATIC_DIR

COPY bin/* /usr/local/sbin/
RUN chmod +x /usr/local/sbin/*

WORKDIR /sbbs

CMD ["sbbs"]
